data_path: "testdata/track_data_ncarstorm_3km_REFL_COM_ws_nc_small/"
patch_radius: 16
mask: False
input_variables: ["REFL_1KM_AGL_curr", "U10_curr", "V10_curr"]
output_variables: ["UP_HELI_MAX_curr"]
meta_variables: ["masks", "i", "j", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
train_start_date: "2011-04-26"
train_end_date: "2011-04-27"
val_start_date: "2011-04-28"
val_end_date: "2011-04-28"
test_start_date: "2011-04-28"
test_end_date: "2011-04-28"
out_path: "model_cnn_20200416/"
classifier: 1
classifier_threshold: 50
random_seed: &seed 88

plot_kwargs:
  REFL_1KM_AGL_curr:
    vmin: 0
    vmax: 80
    cmap: "gist_ncar"
  U10_curr:
    vmin: -20
    vmax: 20
    cmap: "RdBu_r"
  V10_curr:
    vmin: -20
    vmax: 20
    cmap: "RdBu_r"
models:
  cnn_20200416_000:
    min_filters: 8
    filter_width: 3
    filter_growth_rate: 1.5
    pooling_width: 2
    min_data_width: 4
    hidden_activation: "leaky"
    output_type: "sigmoid"
    pooling: "mean"
    loss: "binary_crossentropy"
    learning_rate: 0.01
    batch_size: 8
    epochs: 20
    l2_alpha: 0.001
    use_dropout: 1
    dropout_alpha: 0.5
    dense_neurons: 4
    early_stopping: 0
    verbose: 1

GMM_models:
  GMM_0:
    n_components: 5
    covariance_type: 'full'
    max_iter: 1000
    tol: 0.001
    n_init: 5
    init_params: 'kmeans'
    reg_covar: 0.000001
    verbose: 1
    random_state: *seed

