data_path: "/glade/scratch/dgagne/track_data_ncar_wrfrt_2020_3km_REFL_COM_ws_nc/"
patch_radius: 16
input_variables: ["REFL_COM_curr"]
output_variables: ["UP_HELI_MAX_curr"]
meta_variables: ["masks", "i", "j", "lon", "lat", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
run_start_date: "2020-05-16"
run_end_date: "2020-05-16"
date_format: "%Y%m%d%H"
start_hour: 01
end_hour: 35
out_path: "/glade/work/dgagne/mode_cnn_uh_20200504/"
activation_path: "/glade/scratch/dgagne/mode_cnn_uh_output_wrfrt_2020/"
models:
  cnn_20200504_002:
    neuron_004:
      cmap: "Blues"
      vmin: 0.0
      vmax: 1.6
    neuron_008:
      cmap: "Reds"
      vmin: 0.0
      vmax: 1.6
